version: "3.8"
services:
  db:
    image: postgres:13-alpine
    container_name: runlog_db_production
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"

  web: &web
    build:
      context: .
      dockerfile: Dockerfile.prd
    container_name: runlog_app_production
    stdin_open: true
    tty: true
    tmpfs:
      - /tmp
    environment:
      APP_DB_USERNAME: "postgres"
      APP_DB_PASSWORD: "postgres"
      APP_DB_HOST: "db"
      APP_DB_PORT: "5432"
      RAILS_MASTER_KEY:
      RAILS_ENV: "production"
    depends_on:
      - db
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    expose: ["3000"]
    ports: ["3000:3000"]
    user: root
    working_dir: /app

volumes:
  postgres:
    name: runlog_db_data
