default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['APP_DB_USERNAME'] %>
  password: <%= ENV['APP_DB_PASSWORD'] %>
  host: <%= ENV['APP_DB_HOST'] %>
  port: <%= ENV['APP_DB_PORT'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development

  #host: localhost

  #port: 5432

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
