name: Ruby

on: [push, pull_request]

env:
  RAILS_ENV: test
  DB_HOST: localhost
  DB_USER: rails_app
  DB_PASSWORD: rails_app

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.7
        env:
          POSTGRES_USER: 'rails_app'
          POSTGRES_PASSWORD: 'rails_app'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    - name: Cache bundle directory
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gem-
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4
    - name: yarn install
      run: bin/rails yarn:install
    - name: create database
      run: bin/rails db:create
    - name: create tables
      run: bin/rails db:migrate
    - name: Run tests
      run: bundle exec rake
